# Generated by Django 2.2.1 on 2019-07-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stu_department',
            field=models.CharField(default='no imform. ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='syllabus',
            field=models.TextField(default='no inform. QQ'),
            preserve_default=False,
        ),
    ]
