# Generated by Django 2.2.1 on 2019-07-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190724_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='class_url',
            field=models.URLField(default='no url'),
            preserve_default=False,
        ),
    ]
