# Generated by Django 2.2.1 on 2019-07-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_post_class_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='number',
        ),
        migrations.RemoveField(
            model_name='post',
            name='stu_department',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
        migrations.AddField(
            model_name='post',
            name='add_type',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='class_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='class_order',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='class_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='constraints',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='half_year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='identification_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='required',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='stu_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='class_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='class_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='credit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='syllabus',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='teacher',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
