# Generated by Django 2.2.1 on 2019-07-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20190724_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='click_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='add_type',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='class_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='class_order',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='class_time',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='class_url',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='constraints',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='credit',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='half_year',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='identification_code',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='remark',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='required',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='stu_number',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='syllabus',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='teacher',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
